### ISSUE TITLE
Typo in the method name

### ISSUE THREAD

**Issue by o-vitaliy** [nullgr/app-core#33]
https://github.com/nullgr/app-core/blob/29f7b7776cb21bc69c1bc859ab521ca13d5f7c58/core-hardware/src/main/java/com/nullgr/core/hardware/SupportedFeaturesExtensions.kt#L12

Methods "isCammeraSupported" and "isCammeraAutoFocusSupported" have a typo.  Word "Camera" has only one "m" letter

**Comment by grishko188** [comment]
Fixed in ***1.0.1-alpha.2***
