### ISSUE TITLE
Permission check is missing

### ISSUE THREAD

**Issue by o-vitaliy** [nullgr/app-core#34]
https://github.com/nullgr/app-core/blob/29f7b7776cb21bc69c1bc859ab521ca13d5f7c58/core-hardware/src/main/java/com/nullgr/core/hardware/SupportedFeaturesExtensions.kt#L56

По хорошему, в этом методе стоит проверять, даны ли пермишенны  ACCESS_COARSE_LOCATION or ACCESS_FINE_LOCATION , вместо того что бы оборачивать в try-catch

**Comment by grishko188** [comment]
Permission processing must be performed on the client side.
Try/catch added to avoid ```@throws IllegalArgumentException if provider is null``` .
