### ISSUE TITLE
Nullable pamars in usaces

### ISSUE THREAD

**Issue by o-vitaliy** [nullgr/app-core#37]
https://github.com/nullgr/app-core/blob/29f7b7776cb21bc69c1bc859ab521ca13d5f7c58/core-interactor/src/main/java/com/nullgr/core/interactor/FlowableUseCase.kt#L18

Использование params как nullable делает неудобным реализацию метода buildUseCaseObservable когда параметры обязательные. 
Например, метод который я мог бы написать так
 override fun buildUseCaseObservable(params: Params?): Single<ScreenWrapper>  = repository.getScreenWrapper(params.name)
теперь надо в методе проверять на null  и приходится писать так:
 override fun buildUseCaseObservable(params: Params?): Single<ScreenWrapper> {
        val param = checkNotNull(params)
        return repository.getScreenWrapper(param.name)
    }

Подозреваю, что это была попытка избавиться от обязательных параметров, когда они не нужны. Но лучше передавать Unit, каждый раз проверять на null.

**Comment by vchernyshov** [comment]
Yes, null added to prevent passing unused params or Unit from presenter or viewmodel.
